import streamlit as st
import streamlit.components.v1 as components

st.set_page_config(page_title="Kaisersoft AI", page_icon="⚡", layout="wide", initial_sidebar_state="collapsed")

st.markdown("""
<style>
html,body,[data-testid="stAppViewContainer"],.stApp{margin:0!important;padding:0!important;width:100%!important;min-height:100vh!important;background:#000!important;overflow:hidden!important}
header,footer,#MainMenu,[data-testid="stHeader"],[data-testid="stToolbar"],[data-testid="stDecoration"]{display:none!important;visibility:hidden!important}
.block-container{padding:0!important;margin:0!important;max-width:none!important}
iframe[title="st.components.v1.html"]{position:fixed!important;inset:0!important;width:100vw!important;height:100vh!important;border:0!important;z-index:999999!important}
</style>""", unsafe_allow_html=True)

HTML=r'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><style>
*{box-sizing:border-box;margin:0;padding:0}html,body{width:100%;height:100%;overflow:hidden;background:#000;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif}#app{position:fixed;inset:0;background:radial-gradient(circle at 50% 48%,rgba(0,229,255,.045),transparent 34%),#000;overflow:hidden}
#loading{position:absolute;inset:0;z-index:20;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:24px;background:#000;transition:opacity .9s ease,visibility .9s ease}.done{opacity:0!important;visibility:hidden!important;pointer-events:none}.logo,.title{color:#00e5ff;font-weight:800;letter-spacing:.055em;text-align:center;text-shadow:0 0 14px rgba(0,229,255,.45),0 0 48px rgba(0,229,255,.18)}.logo{font-size:clamp(2.2rem,8vw,5.8rem);line-height:1;margin-bottom:28px}.loading-text{color:rgba(255,255,255,.92);font-size:clamp(.95rem,2.4vw,1.25rem);letter-spacing:.16em;text-align:center;margin-bottom:22px}.progress-wrap{width:min(440px,78vw)}.track{height:4px;background:rgba(255,255,255,.12);border-radius:99px;overflow:hidden}.bar{height:100%;width:0;background:#00e5ff;border-radius:99px;box-shadow:0 0 9px #00e5ff,0 0 25px rgba(0,229,255,.5);transition:width 70ms linear}.percent{color:rgba(255,255,255,.45);font-size:.72rem;letter-spacing:.12em;text-align:center;margin-top:10px}
#experience{position:absolute;inset:0;opacity:0;transition:opacity 1.2s ease}.visible{opacity:1!important}canvas{position:absolute;inset:0;width:100%;height:100%}.center{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;padding:24px;pointer-events:none}.title{font-size:clamp(2.2rem,9vw,6rem);line-height:1.05}.social{position:absolute;z-index:15;left:50%;bottom:clamp(28px,6vh,58px);transform:translateX(-50%)}.instagram{width:44px;height:44px;display:flex;align-items:center;justify-content:center;color:#fff;opacity:.72;text-decoration:none;transition:.2s}.instagram:hover,.instagram:focus{opacity:1;transform:scale(1.08)}.instagram svg{width:30px;height:30px;fill:none;stroke:currentColor;stroke-width:1.8}@media(max-width:480px){.logo,.title{letter-spacing:.02em}.loading-text{letter-spacing:.09em}.progress-wrap{width:82vw}}
</style></head><body><div id="app"><section id="loading"><div class="logo">Kaisersoft AI</div><div class="loading-text">something Powerful is loading...</div><div class="progress-wrap"><div class="track"><div id="bar" class="bar"></div></div><div id="percent" class="percent">0%</div></div></section><section id="experience"><canvas id="fireflies"></canvas><div class="center"><div class="title">Kaisersoft AI</div></div><div class="social"><a class="instagram" href="https://www.instagram.com/kaisersoft.ai" target="_blank" rel="noopener noreferrer" aria-label="Kaisersoft AI on Instagram"><svg viewBox="0 0 24 24"><rect x="3.2" y="3.2" width="17.6" height="17.6" rx="5"></rect><circle cx="12" cy="12" r="4.15"></circle><circle cx="17.55" cy="6.55" r="1" fill="currentColor" stroke="none"></circle></svg></a></div></section></div><script>
const canvas=document.getElementById('fireflies'),ctx=canvas.getContext('2d');let W,H,D,ps=[],raf;function resize(){D=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*D;canvas.height=H*D;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(D,0,0,D,0,0);make()}function make(){const n=Math.max(28,Math.min(110,Math.round(W*H/14500)));ps=Array.from({length:n},()=>({x:Math.random()*W,y:Math.random()*H,vx:(Math.random()-.5)*.24,vy:(Math.random()-.5)*.24,r:.7+Math.random()*1.8,p:Math.random()*Math.PI*2,s:.008+Math.random()*.018,g:.35+Math.random()*.65}))}function draw(){ctx.clearRect(0,0,W,H);for(const p of ps){p.x+=p.vx;p.y+=p.vy;p.p+=p.s;if(p.x<-20)p.x=W+20;if(p.x>W+20)p.x=-20;if(p.y<-20)p.y=H+20;if(p.y>H+20)p.y=-20;const a=p.g*(.35+.65*((Math.sin(p.p)+1)/2)),q=ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,p.r*9);q.addColorStop(0,`rgba(0,229,255,${a})`);q.addColorStop(.18,`rgba(0,229,255,${a*.45})`);q.addColorStop(1,'rgba(0,229,255,0)');ctx.beginPath();ctx.fillStyle=q;ctx.arc(p.x,p.y,p.r*9,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.fillStyle=`rgba(220,255,255,${Math.min(1,a+.12)})`;ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}raf=requestAnimationFrame(draw)}addEventListener('resize',resize,{passive:true});resize();const loading=document.getElementById('loading'),exp=document.getElementById('experience'),bar=document.getElementById('bar'),pct=document.getElementById('percent'),start=performance.now(),duration=3600;function load(t){const p=Math.min(100,(t-start)/duration*100);bar.style.width=p+'%';pct.textContent=Math.round(p)+'%';if(p<100)return requestAnimationFrame(load);setTimeout(()=>{loading.classList.add('done');exp.classList.add('visible');if(!raf)raf=requestAnimationFrame(draw)},180)}requestAnimationFrame(load);
</script></body></html>'''

components.html(HTML,height=1000,scrolling=False)
